name: gamestream_http_client
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  uuid: ^3.0.4
  http: ^0.13.5
  typedef: ^1.0.12

dev_dependencies:
  lints: ^2.0.0
