name: gamestream_users
description: A restful server for accessing user information
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  http: ^0.13.4
  typedef: ^1.0.12
  uuid: ^4.1.0
  crypto: ^3.0.3
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0

