name: bleed_server
description: The Websocket server for gamestream
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  lemon_byte: ^1.0.12
  lemon_math: ^1.2.12
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  uuid: ^3.0.4
  http: ^0.13.5
  typedef: ^1.0.8
  fast_noise: ^1.0.1